services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: SUPABASE_URL
        fromEnvVar: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromEnvVar: SUPABASE_SERVICE_ROLE_KEY