name: CI/CD
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies and run backend tests
        run: |
          cd backend
          pip install -r requirements.txt
          pytest
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend and run Playwright tests
        run: |
          cd frontend
          npm install
          npx playwright install
          npx playwright test